### PR TITLE
Remove `FixturesTrait` dependency on environment

### LINKED ISSUE #43: SQLite schema is not instantiated for non-test environment
When running the test suite via a different environment as `test`, the tests fail because the sqlite database does not seem to get instantiated (migrations do not get executed first?).

Changing `\Liip\TestFixturesBundle\Test\FixturesTrait::$environment` to the expected environment manually fixes the below.

### Preconditions

1. php 7.3
2. symfony 4.3
3. LiipTestFixturesBundle 1.3.2
4. for env `test` and `int` Doctrine configuration is setup with `pdo_sqlite` driver and `"%kernel.cache_dir%/test.db"` as path
5. am running phpunit via docker:

> docker run --rm -v $(DIR):/app -w /app -e APP_ENV=int composer bin/phpunit --configuration phpunit.integration.xml

### Steps to reproduce

1. write a functional test that loads a fixture
2. running on app environment `test` works fine
3. changing app environment to `int` and run tests

### Expected result

Tests should pass when running on different environment. Fixtures should get loaded

### Actual result

* Tests fail, table does not seem to be there.

image

* The "test.db" file does get written to the `/cache/int` folder, but the db file is empty. The db file for environment `test` is not empty, it seems to be instantiated ok

* The connection seems ok. After copying the above instantiated `test.db` to the `int` cache folder, and running the tests again, the fixture can get created.

* `phpunit.integration.xml` is an identical copy of a normal `phpunit.xml.dist`, but with `APP_ENV` set to `int`

### PR DESCRIPTION
**Pull request by rvanlaak**
fixes #43 by letting the kernel decide on the active environment (as in `KernelTestCase::createKernel`)

👏 for #26 that is deprecating the whole trait

### CODE REVIEW

**Comment by rvanlaak** [comment]
cc @alexislefebvre

File: src/Test/FixturesTrait.php [hunk 1]
```diff
@@ -159,4 +158,20 @@ protected function tearDown(): void
 
         parent::tearDown();
     }
+
+    /**
+     * @see KernelTestCase::createKernel()
+     */
+    private function determineEnvironment()
+    {
+        if (isset($_ENV['APP_ENV'])) {
```
Comment (alexislefebvre) [inline src/Test/FixturesTrait.php]: Is it possible that this value is never defined?

Comment (rvanlaak) [reply src/Test/FixturesTrait.php]: As example, phpunit.xml.dist would allow you to set both the server and env parameters:

```
<env name="APP_ENV" value="test" />
<server name="APP_ENV" value="test" />
```

Not sure, but I even have the idea that `env` has precedence over `server`. You could define a different environment variable in your `docker-compose` config, and let tests run on the environment you expect by setting env in `phpunit.xml.dist`.

**Comment by rvanlaak** [comment]
Not being able to override environment blocks us in creating an extra test environment.

@alexislefebvre any remaining concerns in getting this merged?

**Comment by alexislefebvre** [comment]
Thanks for the PR!

You can try the last release: https://github.com/liip/LiipTestFixturesBundle/releases/tag/1.4.0
